### ISSUE TITLE
Step 4 ligo error

### ISSUE THREAD

**Issue by songproducer** [marigold-dev/training-dapp-1#1]
> ligo compile contract ./smartcontract/pokeGame.jsligo --output-file pokeGame.tz

Returns an error:

> ligo: command `compile' ambiguous and could be one of `compile-contract',
>       `compile-expression', `compile-parameter' or `compile-storage'
> Usage: ligo COMMAND ...

So I tried:

> ligo compile-contract ./smartcontract/pokeGame.jsligo --output-file pokeGame.tz

but got:

>ligo: required argument ENTRY_POINT is missing
>Usage: ligo compile-contract [OPTION]... SOURCE_FILE ENTRY_POINT

**Comment by zamrokk** [comment]
which client version / OS  do you use ?

try to add

`-e main`  argument
or
`--entrypoint main`  argument

**Comment by songproducer** [comment]
ligo: unknown option `--entrypoint'.
ligo: unknown option `-e'.

MacOS 
ligo --version
Rolling release
Commit SHA: ffa39cce077e1426d15d3ce3bdfe5009481387e2
Commit Date: 2021-07-30T14:39:17+00:00

**Comment by d-plaindoux** [comment]
This is an old version (near 0.22.0). If you use Docker you should remove the current image. Then redoing a compilation will download the latest version.

**Comment by songproducer** [comment]
I removed the docker image then tried to reinstall ligo by using the command shown here:
https://ligolang.org/docs/intro/installation/
docker run --rm -v "$PWD":"$PWD" -w "$PWD" ligolang/ligo:0.41.0

but I ended up with the same version.

**Comment by zamrokk** [comment]
What gives ?
`which ligo`

**Comment by songproducer** [comment]
/usr/local/bin/ligo

**Comment by zamrokk** [comment]
That should be the old version where the exe is pointing to. Just remove it

**Comment by songproducer** [comment]
Thanks,
Now I get this

ligo compile contract ./smartcontract/pokeGame.jsligo --output-file pokeGame.tz
./smartcontract/pokeGame.jsligo: No such file or directory

but running ls shows it's there:
ls
dapp		smartcontract
(base) leotreasure@Leos-MacBook-Pro-2 solution % cd smartcontract 
(base) leotreasure@Leos-MacBook-Pro-2 smartcontract % ls
pokeGame.jsligo

**Comment by zamrokk** [comment]
https://docs.docker.com/engine/reference/commandline/run/

`Mount volume (-v, --read-only) — Volumes can be used in combination with --read-only to control where a container writes files. The --read-only flag mounts ...`

That's why I don't like using Docker for ligo CLI , you need to mount a volume otherwise your ligo exe will not be able to see the local file of your machine

**Comment by songproducer** [comment]
Is this right?

docker run -v /Users/leotreasure/training-dapp-1:/solution -w /solution -i -t ligolang/ligo:0.41.0 compile contract ./solution/smartcontract/pokeGame.jsligo --output-file pokeGame.tz

cat ../pokeGame.tz 
```
{ parameter unit ;
  storage (set address) ;
  code { CDR ; PUSH bool True ; SOURCE ; UPDATE ; NIL operation ; PAIR } }

```

**Comment by zamrokk** [comment]
Nice 👍
