### ISSUE TITLE
Dapp Step 1 : Create react app - CRA is outdated

### ISSUE THREAD

**Issue by BearCooder** [marigold-dev/training-dapp-1#6]
Hello Team,

please do not use `create-react-app `in your tutorials/guides as it is outdated and will be not maintained anymore! 
Read the comment of a maintainer in this discussion:
Its a long comment so you can scroll down at the bottom to see the conclusion:
https://github.com/reactjs/reactjs.org/pull/5487#issuecomment-1409720741
Just to clarify: P**lease continue to use React but not the `create-react-app` template.**
I strongly suggest to use either the **React Vite template** or the **React Metaframework Next.js**.
Easy to do with this simple command:
`npm create vite@latest my-react-app --template react-ts`

See here for more: 
https://vitejs.dev/guide/

And for next.js there is even a guide how to migrate form create react app template projects! 
https://nextjs.org/docs/migrating/from-create-react-app

And how to create a nextjs app from scratch:
https://nextjs.org/docs/api-reference/create-next-app

Please make the switch from the create react template asap, its just a few clicks but if not this will hurt only people in the longterm that will use CRA.

If you are curious about more/other state of the art solutions to use I can recommend this great graphic as overview:
https://twitter.com/t3dotgg/status/1612980211393638401

Thank you!

**Comment by zamrokk** [comment]
@BearCooder thank you for pointing out this.
I note this on my todo list, this is a relevant argument

**Comment by BearCooder** [comment]
Thats great to hear, thanks and looking forward to it!

**Comment by BearCooder** [comment]
Any ETA for the migration?

**Comment by zamrokk** [comment]
I was waiting for ligo V1 to redo all trainings

**Comment by zamrokk** [comment]
moving to vite rn
