### ISSUE TITLE
The dipdup/tzkt-api package is deprecated

### ISSUE THREAD

**Issue by dvkam** [marigold-dev/training-dapp-1#8]
During the process of moving from CRA to Vite I discovered that the dipdup/tzkt-api package is deprecated. After asking the Baking Bad team they said it's better to use https://github.com/tzkt/api-sdk-ts instead. 

![image_2023-06-27_13-04-59](https://github.com/marigold-dev/training-dapp-1/assets/82422481/1ebdf4ea-c9bd-43e9-9e2e-0b5f1ea4ce72)

Opening issue to keep track of it after the migration.

**Comment by zamrokk** [comment]
yep, part of vite migration too
